#basic
dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorflow"
project_name: "XuanCe_Benchmark"
logger: "tensorboard"  # Choices: "tensorboard", "wandb".
wandb_user_name: "your_user_name"

render: True
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
test_steps: 2000

device: "cuda:0"







agent: "DQN"
env_name: "Classic Control"
env_id: "ChaosControlTest"
vectorize: "DummyVecEnv"
policy: "Basic_Q_network"
representation: "Basic_MLP"
runner: "DRL"

render: False # Whether to render the environment when testing.
render_mode: 'human' # Choices: 'human', 'rgb_array'.
device: "cuda:0"  # Choose an calculating device.
representation_hidden_size: [198,]
q_hidden_size: [198,]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 50000
batch_size: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 1
end_greedy: 0.01
decay_step_greedy: 150000
sync_frequency: 50
training_frequency: 1
running_steps: 300000  # 200k
#running_steps: 2000
start_training: 1000

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 20000
test_episode: 1
log_dir: "./logs/dqn/MLP"
model_dir: "./models/dqn/MLP"
